//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.12 at 02:18:08 PM CEST 
//


package de.galileocomputing.schroedinger.java.kapitel14.terminkalender.jaxb.generiert;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the de.galileocomputing.schroedinger.java.kapitel14.terminkalender.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: de.galileocomputing.schroedinger.java.kapitel14.terminkalender.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Terminkalender }
     * 
     */
    public Terminkalender createTerminkalender() {
        return new Terminkalender();
    }

    /**
     * Create an instance of {@link Besitzer }
     * 
     */
    public Besitzer createBesitzer() {
        return new Besitzer();
    }

    /**
     * Create an instance of {@link Termine }
     * 
     */
    public Termine createTermine() {
        return new Termine();
    }

    /**
     * Create an instance of {@link Termin }
     * 
     */
    public Termin createTermin() {
        return new Termin();
    }

}
