//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.12 at 02:25:54 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.galileocomputing.de/schroedinger/musiksammlung", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package de.galileocomputing.schroedinger.java.kapitel14.musiksammlung.jaxb;
