//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.12 at 02:25:54 PM CEST 
//


package de.galileocomputing.schroedinger.java.kapitel14.musiksammlung.jaxb.generiert;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the de.galileocomputing.schroedinger.java.kapitel14.musiksammlung.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: de.galileocomputing.schroedinger.java.kapitel14.musiksammlung.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Musiksammlung }
     * 
     */
    public Musiksammlung createMusiksammlung() {
        return new Musiksammlung();
    }

    /**
     * Create an instance of {@link Kuenstler }
     * 
     */
    public Kuenstler createKuenstler() {
        return new Kuenstler();
    }

    /**
     * Create an instance of {@link Alben }
     * 
     */
    public Alben createAlben() {
        return new Alben();
    }

    /**
     * Create an instance of {@link Album }
     * 
     */
    public Album createAlbum() {
        return new Album();
    }

}
